name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['master']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - run: sbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - run: sbt check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - run: sbt test
